### ISSUE TITLE
Add `name` param to routes

### ISSUE THREAD

**Issue by nicooprat** [magicspon/barba-router#1]
Would be easier & more maintainable to specify names for routes, like:

```js
export default [
	{
		path: '/',
		name: 'home', // this
		view: Home
	},
]
``` 

For now, the object given in routes events doesn't contain undocumented params: 

```js
export const Home = {
	onEnter({ from, to, next }) {
		console.log(to.name) // null
		next()
	},
}
```

What do you think? Should we let any other arbitrary property being added?

**Comment by magicspon** [comment]
I was thinking the name property could be used to match a route using a data-attribute on the link clicked.  I've not built that functionality yet.

**Comment by magicspon** [comment]
open to PR's

**Comment by magicspon** [comment]
@nicooprat 

I've add the following functionality...

data-route attribute on the link to match against a 'route' name
```
<a href="/page-1" data-route="home">Page 1</a>
```

route item
```

	{
		view: Home,
		name: 'home'
	},
```

**Comment by magicspon** [comment]
http://barba-router.surge.sh/

**Comment by nicooprat** [comment]
That was fast! Nice one.
