### ISSUE TITLE
`onEnter` not fired on first view

### ISSUE THREAD

**Issue by nicooprat** [magicspon/barba-router#2]
Navigate to http://sponjs.surge.sh/test/list/ & hit reload. The body bgcolor is not applied. 

Should we expect the CSS to be the way it is at page load, or always apply `onEnter` (in which case `from` would be `null`)?

**Comment by magicspon** [comment]
Currently as designed... 

Could look into changing this behaviour though.

maybe an option, `triggerOnLoad: true` or shomething

**Comment by magicspon** [comment]
triggerOnLoad option added:
```

new Router({
	routes,
	triggerOnLoad: true,
	onChange: [],
	onReady: [],
	onComplete: [],
	navigation: ['header > ul', 'footer > ul'],
	activeClass: 'is-current',
	activeParentClass: 'is-current-child'
}).start()

```
