### ISSUE TITLE
How to manage GET parameters

### ISSUE THREAD

**Issue by nicooprat** [magicspon/barba-router#3]
How should we manage GET params, like `/page1` and `page1?filter=articles`? Should the same route be triggered again with some additional parameters? Something like:

```js
// /page/1?filter=articles
export const Page1 = {
  onEnter({from, to, next}) {
    console.log(to)
    /*
    {
      "path": "/",
      "params": {
        "id" : "1"
      },
      "getParams": {
        "filter" : "articles"
      },
      "container": {...}
    }
    */
  },
}
```

**Comment by magicspon** [comment]
This is currently not possible... should be fairly simple to add though.

having said that, i'm not going to have a chance to look at anything this week, mega busy.

I'm using https://github.com/pillarjs/path-to-regexp for matching urls to routes.

**Comment by nicooprat** [comment]
Just created a small PR that seems to work. Some enhancements could certainly be made. Tell me what you think.

Unfortunately `path-to-regexp` doesn't handle GET parameters at all by the way.

**Comment by magicspon** [comment]
Hey...

I added a parseQuery function to the utils library last night.

also, I removed _this.currentRoute and _this.match from the from/to props, and just included the bits that would be useful, i.e. all the stuff minus the views object.

anyhow, I'll take a look at your PR tonight

cheers

**Comment by magicspon** [comment]
Hello,

Sorry for the epic delay getting back to you... 

Anyhow, I've just pushed up a rewrite...

Same API... just a bit neater

you can see in action here: http://sharp-booth-fc3141.netlify.com/

**Comment by nicooprat** [comment]
No worries, nice work! What does this `name: '#f39c97'` mean?

**Comment by magicspon** [comment]
You can give each route a name. In the example I'm using the name to store a background color.

**Comment by nicooprat** [comment]
That's what I thought, it could be a bit disturbing for new comers I guess :)

I think the demo should contain at least one link with a query. Small suggestion too, the `query` parameter could be an object like `{query: {filter: 'articles', page: 2}}` instead of a plain string (eg. https://stackoverflow.com/a/8649003/758728).

**Comment by magicspon** [comment]
Sure thing... i'll take a look later

this is what's happening under the hood:

I'll use the queryKey instaed of query.

```
queryKey: [object Object] {
    feature: "2",
    query: "test"
  }
```

http://jsbin.com/sewinup/edit?js,console,output

**Comment by magicspon** [comment]
done: 
https://github.com/magicspon/barba-router/commit/935240daa6bfac6ccbd20d780b36aa520db717de

**Comment by nicooprat** [comment]
Easy :) great!

**Comment by magicspon** [comment]
added an example to boot!
http://sharp-booth-fc3141.netlify.com/page-3?page=20&name=gary
