### ISSUE TITLE
Add onInit callback

### ISSUE THREAD

**Issue by nicooprat** [magicspon/barba-router#8]
Seems like `onChange`, `onReady` and `onComplete` are called for each route. Would be useful to have a method called once when BarbaRouter is initialized, sth like:

```js
new BarbaRouter({
  onInit() {...}
})
```

Would be cleaner if the three callbacks mentioned above are renamed like `onRouteReady()`?

👌

**Comment by magicspon** [comment]
Heyo...

Yup... good shout

I'd like to keep it in the same format as the other methods...

i.e.

```
new BarbaRouter({
  onInit: [
   fn1,
   () => log('hello'),
   etc
  ]
})
```

each function would be passed the current route information

**Comment by magicspon** [comment]
@nicooprat heyo... apologises I never got round to doing this... 

however... i have been working on a new thing... 

https://github.com/magicspon/mud-fractal/tree/master/src/js#router

The router part is essentially a rewrite of barba... but with the "routes" object fully baked in... You have total control of the adding/removing of html of change (checkout the pagination here (https://sponjs.netlify.com/blog/) - hello infinite scroll?!)...  it's got some other pretty sweet features too! 

anyhow, i've not used this on any production sites yet, and I need to improve the tests... but it appears it works!

Would be great to get some input/feedback.

(if you want to play with the code, at the moment, your best bet is to fork/clone the repo... `npm install`, the `npm start`)

https://sponjs.netlify.com/

cheers

**Comment by nicooprat** [comment]
Hi,

No worries I stopped trying to use Barba in any way for now :) I'll take a look at your new code asap.

Also did you see this remake of Barba? https://inside.dogstudio.be/highway-the-only-modern-flexible-js-transitions-manager-youll-ever-need-e6b9f1ab9a6b

Cheers!

**Comment by magicspon** [comment]
ooh.. nope i'd not seen that...  nice one.

**Comment by magicspon** [comment]
@nicooprat .... yup... that looks very nice.

it's much lighter than my thing, i've relied on dependencies for things like events, delegation and history, and mine if entirely built around the 'routes' array, no direct relation to the dom.  Also, it's kinda tied in with the way i manage adding/removing dom functionality (for regular non react/vue/etal sites).

it does look nice though (might pinch some code!)!
